name: Test
run-name: Test • ${{ github.event.head_commit.message || github.event.pull_request.title || 'Manual trigger' }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck
        run: |
          shellcheck --version
          make lint

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          wget https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64 -O shfmt
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/
          shfmt --version

      - name: Check formatting
        run: make format-check

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew (Linux)
        if: runner.os == 'Linux'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" </dev/null
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install dependencies
        run: make install-deps

      - name: Run tests
        run: make test

      - name: Check test coverage
        run: bash dev/coverage.sh
